// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  filo-Spin-SP513
// DateTime: 6/4/2018 1:08:32 PM
// UserName: filo
// Input file <FParser/gppg/grammar.y - 6/4/2018 1:08:28 PM>

// options: lines

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using FFC.FAST;
using FFC.FLexer;

namespace FFC.FParser
{
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal partial class Parser: ShiftReduceParser<TValue, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[112];
  private static State[] states = new State[206];
  private static string[] nonTerms = new string[] {
      "starting", "$accept", "dec_list", "declaration", "identifier", "opt_type", 
      "expr", "func_def", "type", "func_type", "tuple_type", "array_type", "map_type", 
      "expr2", "secondary", "primary", "func_call", "indexer", "value", "cond", 
      "array_def", "map_def", "tuple_def", "opt_params", "func_body", "param_list", 
      "param", "stm_list", "statement", "assignment", "if_stm", "loop_stm", "return_stm", 
      "break_stm", "cont_stm", "print_stm", "opt_exprs", "expr_list", "loop_header", 
      "pair_list", "pair", "tuple_elist", "tuple_elem", "type_list", };

  static Parser() {
    states[0] = new State(new int[]{4,29},new int[]{-1,1,-3,3,-4,205,-5,6});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{3,4,4,29},new int[]{-4,5,-5,6});
    states[4] = new State(-2);
    states[5] = new State(-4);
    states[6] = new State(new int[]{13,89,40,-8},new int[]{-6,7});
    states[7] = new State(new int[]{40,8});
    states[8] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-7,9,-8,11,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[9] = new State(new int[]{14,10});
    states[10] = new State(-5);
    states[11] = new State(-6);
    states[12] = new State(new int[]{51,13,27,163,28,165,29,167,30,169,31,171,32,173,33,175,34,177,35,179,17,181,18,183,15,185,16,187,57,189,53,65,11,85,14,-22,12,-22,52,-22,54,-22,42,-22,43,-22,44,-22,13,-22,56,-22,48,-22},new int[]{-18,64});
    states[13] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69,52,-74},new int[]{-37,14,-38,16,-14,42,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[14] = new State(new int[]{52,15});
    states[15] = new State(-73);
    states[16] = new State(new int[]{12,17,52,-75,54,-75});
    states[17] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-14,18,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[18] = new State(-77);
    states[19] = new State(-20);
    states[20] = new State(-38);
    states[21] = new State(-41);
    states[22] = new State(-46);
    states[23] = new State(-47);
    states[24] = new State(-48);
    states[25] = new State(-49);
    states[26] = new State(-50);
    states[27] = new State(-51);
    states[28] = new State(-52);
    states[29] = new State(-7);
    states[30] = new State(-42);
    states[31] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,32,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[32] = new State(new int[]{42,33});
    states[33] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-14,34,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[34] = new State(new int[]{43,35});
    states[35] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-14,36,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[36] = new State(new int[]{44,37});
    states[37] = new State(-53);
    states[38] = new State(-43);
    states[39] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69,54,-74},new int[]{-37,40,-38,16,-14,42,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[40] = new State(new int[]{54,41});
    states[41] = new State(-91);
    states[42] = new State(-76);
    states[43] = new State(-44);
    states[44] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69,56,-93,12,-93},new int[]{-40,45,-41,204,-14,49,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[45] = new State(new int[]{56,46,12,47});
    states[46] = new State(-92);
    states[47] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-41,48,-14,49,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[48] = new State(-95);
    states[49] = new State(new int[]{13,50});
    states[50] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-14,51,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[51] = new State(-96);
    states[52] = new State(-45);
    states[53] = new State(new int[]{4,29,5,22,6,23,7,24,8,25,9,26,10,27,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-42,54,-43,203,-5,58,-14,202,-7,19,-15,12,-16,20,-19,21,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[54] = new State(new int[]{52,55,12,56});
    states[55] = new State(-97);
    states[56] = new State(new int[]{4,29,5,22,6,23,7,24,8,25,9,26,10,27,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-43,57,-5,58,-14,202,-7,19,-15,12,-16,20,-19,21,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[57] = new State(-99);
    states[58] = new State(new int[]{40,59,51,-52,27,-52,28,-52,29,-52,30,-52,31,-52,32,-52,33,-52,34,-52,35,-52,17,-52,18,-52,15,-52,16,-52,57,-52,53,-52,11,-52,52,-52,12,-52});
    states[59] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-14,60,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[60] = new State(-100);
    states[61] = new State(-39);
    states[62] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53},new int[]{-15,63,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[63] = new State(new int[]{51,13,53,65,11,85,14,-36,12,-36,52,-36,54,-36,42,-36,43,-36,44,-36,13,-36,56,-36,48,-36},new int[]{-18,64});
    states[64] = new State(-40);
    states[65] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-14,66,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[66] = new State(new int[]{54,67});
    states[67] = new State(-102);
    states[68] = new State(-21);
    states[69] = new State(new int[]{51,70});
    states[70] = new State(new int[]{4,29,52,-55},new int[]{-24,71,-26,195,-27,201,-5,198});
    states[71] = new State(new int[]{52,72});
    states[72] = new State(new int[]{13,89,37,-8,26,-8},new int[]{-6,73});
    states[73] = new State(new int[]{37,75,26,191},new int[]{-25,74});
    states[74] = new State(-54);
    states[75] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,121,53,39,55,44,51,53,46,137,45,142,38,145,49,150,50,153,39,156,48,-82},new int[]{-28,76,-29,161,-17,79,-15,81,-16,20,-19,21,-5,88,-20,30,-21,38,-22,43,-23,52,-30,129,-4,130,-31,131,-32,132,-39,133,-33,144,-34,149,-35,152,-36,155});
    states[76] = new State(new int[]{44,77,5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,121,53,39,55,44,51,53,46,137,45,142,38,145,49,150,50,153,39,156,48,-82},new int[]{-29,78,-17,79,-15,81,-16,20,-19,21,-5,88,-20,30,-21,38,-22,43,-23,52,-30,129,-4,130,-31,131,-32,132,-39,133,-33,144,-34,149,-35,152,-36,155});
    states[77] = new State(-60);
    states[78] = new State(-63);
    states[79] = new State(new int[]{14,80,51,-39,25,-39,53,-39,11,-39,27,-39,28,-39,29,-39,30,-39,31,-39,32,-39,33,-39,34,-39,35,-39,17,-39,18,-39,15,-39,16,-39,57,-39,43,-39});
    states[80] = new State(-64);
    states[81] = new State(new int[]{51,13,25,82,53,65,11,85},new int[]{-18,64});
    states[82] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-14,83,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[83] = new State(new int[]{14,84});
    states[84] = new State(-78);
    states[85] = new State(new int[]{6,87,4,29},new int[]{-5,86});
    states[86] = new State(-103);
    states[87] = new State(-104);
    states[88] = new State(new int[]{13,89,51,-52,25,-52,53,-52,11,-52,27,-52,28,-52,29,-52,30,-52,31,-52,32,-52,33,-52,34,-52,35,-52,17,-52,18,-52,15,-52,16,-52,57,-52,43,-52,40,-8},new int[]{-6,7});
    states[89] = new State(new int[]{19,91,20,92,21,93,22,94,23,95,24,96,36,98,51,105,53,111,55,115},new int[]{-9,90,-10,97,-11,104,-12,110,-13,114});
    states[90] = new State(-9);
    states[91] = new State(-10);
    states[92] = new State(-11);
    states[93] = new State(-12);
    states[94] = new State(-13);
    states[95] = new State(-14);
    states[96] = new State(-15);
    states[97] = new State(-16);
    states[98] = new State(new int[]{51,99});
    states[99] = new State(new int[]{19,91,20,92,21,93,22,94,23,95,24,96,36,98,51,105,53,111,55,115,52,-106,12,-106},new int[]{-44,100,-9,120,-10,97,-11,104,-12,110,-13,114});
    states[100] = new State(new int[]{52,101,12,108});
    states[101] = new State(new int[]{13,102});
    states[102] = new State(new int[]{19,91,20,92,21,93,22,94,23,95,24,96,36,98,51,105,53,111,55,115},new int[]{-9,103,-10,97,-11,104,-12,110,-13,114});
    states[103] = new State(-105);
    states[104] = new State(-17);
    states[105] = new State(new int[]{19,91,20,92,21,93,22,94,23,95,24,96,36,98,51,105,53,111,55,115,52,-106,12,-106},new int[]{-44,106,-9,120,-10,97,-11,104,-12,110,-13,114});
    states[106] = new State(new int[]{52,107,12,108});
    states[107] = new State(-110);
    states[108] = new State(new int[]{19,91,20,92,21,93,22,94,23,95,24,96,36,98,51,105,53,111,55,115},new int[]{-9,109,-10,97,-11,104,-12,110,-13,114});
    states[109] = new State(-108);
    states[110] = new State(-18);
    states[111] = new State(new int[]{19,91,20,92,21,93,22,94,23,95,24,96,36,98,51,105,53,111,55,115},new int[]{-9,112,-10,97,-11,104,-12,110,-13,114});
    states[112] = new State(new int[]{54,113});
    states[113] = new State(-109);
    states[114] = new State(-19);
    states[115] = new State(new int[]{19,91,20,92,21,93,22,94,23,95,24,96,36,98,51,105,53,111,55,115},new int[]{-9,116,-10,97,-11,104,-12,110,-13,114});
    states[116] = new State(new int[]{13,117});
    states[117] = new State(new int[]{19,91,20,92,21,93,22,94,23,95,24,96,36,98,51,105,53,111,55,115},new int[]{-9,118,-10,97,-11,104,-12,110,-13,114});
    states[118] = new State(new int[]{56,119});
    states[119] = new State(-111);
    states[120] = new State(-107);
    states[121] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,122,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[122] = new State(new int[]{42,123});
    states[123] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,121,53,39,55,44,51,53,18,62,36,69,46,137,45,142,38,145,49,150,50,153,39,156,48,-82},new int[]{-14,34,-28,124,-7,19,-15,162,-16,20,-19,21,-5,88,-20,30,-21,38,-22,43,-23,52,-17,79,-8,68,-29,161,-30,129,-4,130,-31,131,-32,132,-39,133,-33,144,-34,149,-35,152,-36,155});
    states[124] = new State(new int[]{44,125,43,126,5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,121,53,39,55,44,51,53,46,137,45,142,38,145,49,150,50,153,39,156,48,-82},new int[]{-29,78,-17,79,-15,81,-16,20,-19,21,-5,88,-20,30,-21,38,-22,43,-23,52,-30,129,-4,130,-31,131,-32,132,-39,133,-33,144,-34,149,-35,152,-36,155});
    states[125] = new State(-79);
    states[126] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,121,53,39,55,44,51,53,46,137,45,142,38,145,49,150,50,153,39,156,48,-82},new int[]{-28,127,-29,161,-17,79,-15,81,-16,20,-19,21,-5,88,-20,30,-21,38,-22,43,-23,52,-30,129,-4,130,-31,131,-32,132,-39,133,-33,144,-34,149,-35,152,-36,155});
    states[127] = new State(new int[]{44,128,5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,121,53,39,55,44,51,53,46,137,45,142,38,145,49,150,50,153,39,156,48,-82},new int[]{-29,78,-17,79,-15,81,-16,20,-19,21,-5,88,-20,30,-21,38,-22,43,-23,52,-30,129,-4,130,-31,131,-32,132,-39,133,-33,144,-34,149,-35,152,-36,155});
    states[128] = new State(-80);
    states[129] = new State(-65);
    states[130] = new State(-66);
    states[131] = new State(-67);
    states[132] = new State(-68);
    states[133] = new State(new int[]{48,134});
    states[134] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,121,53,39,55,44,51,53,46,137,45,142,38,145,49,150,50,153,39,156,48,-82},new int[]{-28,135,-29,161,-17,79,-15,81,-16,20,-19,21,-5,88,-20,30,-21,38,-22,43,-23,52,-30,129,-4,130,-31,131,-32,132,-39,133,-33,144,-34,149,-35,152,-36,155});
    states[135] = new State(new int[]{44,136,5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,121,53,39,55,44,51,53,46,137,45,142,38,145,49,150,50,153,39,156,48,-82},new int[]{-29,78,-17,79,-15,81,-16,20,-19,21,-5,88,-20,30,-21,38,-22,43,-23,52,-30,129,-4,130,-31,131,-32,132,-39,133,-33,144,-34,149,-35,152,-36,155});
    states[136] = new State(-81);
    states[137] = new State(new int[]{4,29,5,22,6,23,7,24,8,25,9,26,10,27,41,31,53,39,55,44,51,53,18,62},new int[]{-5,138,-7,141,-15,12,-16,20,-19,21,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[138] = new State(new int[]{47,139,51,-52,27,-52,28,-52,29,-52,30,-52,31,-52,32,-52,33,-52,34,-52,35,-52,17,-52,18,-52,15,-52,16,-52,57,-52,53,-52,11,-52,48,-52});
    states[139] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,140,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[140] = new State(-83);
    states[141] = new State(-84);
    states[142] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,143,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[143] = new State(-85);
    states[144] = new State(-69);
    states[145] = new State(new int[]{14,146,5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-14,147,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[146] = new State(-86);
    states[147] = new State(new int[]{14,148});
    states[148] = new State(-87);
    states[149] = new State(-70);
    states[150] = new State(new int[]{14,151});
    states[151] = new State(-88);
    states[152] = new State(-71);
    states[153] = new State(new int[]{14,154});
    states[154] = new State(-89);
    states[155] = new State(-72);
    states[156] = new State(new int[]{51,157});
    states[157] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69,52,-74},new int[]{-37,158,-38,16,-14,42,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[158] = new State(new int[]{52,159});
    states[159] = new State(new int[]{14,160});
    states[160] = new State(-90);
    states[161] = new State(-62);
    states[162] = new State(new int[]{51,13,27,163,28,165,29,167,30,169,31,171,32,173,33,175,34,177,35,179,17,181,18,183,15,185,16,187,57,189,25,82,53,65,11,85,43,-22},new int[]{-18,64});
    states[163] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,164,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[164] = new State(-23);
    states[165] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,166,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[166] = new State(-24);
    states[167] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,168,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[168] = new State(-25);
    states[169] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,170,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[170] = new State(-26);
    states[171] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,172,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[172] = new State(-27);
    states[173] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,174,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[174] = new State(-28);
    states[175] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,176,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[176] = new State(-29);
    states[177] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,178,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[178] = new State(-30);
    states[179] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,180,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[180] = new State(-31);
    states[181] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,182,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[182] = new State(-32);
    states[183] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,184,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[184] = new State(-33);
    states[185] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,186,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[186] = new State(-34);
    states[187] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62},new int[]{-7,188,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[188] = new State(-35);
    states[189] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53},new int[]{-15,190,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61});
    states[190] = new State(new int[]{51,13,53,65,11,85,14,-37,12,-37,52,-37,54,-37,42,-37,43,-37,44,-37,13,-37,56,-37,48,-37},new int[]{-18,64});
    states[191] = new State(new int[]{51,192});
    states[192] = new State(new int[]{5,22,6,23,7,24,8,25,9,26,10,27,4,29,41,31,53,39,55,44,51,53,18,62,36,69},new int[]{-14,193,-7,19,-15,12,-16,20,-19,21,-5,28,-20,30,-21,38,-22,43,-23,52,-17,61,-8,68});
    states[193] = new State(new int[]{52,194});
    states[194] = new State(-61);
    states[195] = new State(new int[]{12,196,52,-56});
    states[196] = new State(new int[]{4,29},new int[]{-27,197,-5,198});
    states[197] = new State(-58);
    states[198] = new State(new int[]{13,199});
    states[199] = new State(new int[]{19,91,20,92,21,93,22,94,23,95,24,96,36,98,51,105,53,111,55,115},new int[]{-9,200,-10,97,-11,104,-12,110,-13,114});
    states[200] = new State(-59);
    states[201] = new State(-57);
    states[202] = new State(-101);
    states[203] = new State(-98);
    states[204] = new State(-94);
    states[205] = new State(-3);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{-3,3});
    rules[3] = new Rule(-3, new int[]{-4});
    rules[4] = new Rule(-3, new int[]{-3,-4});
    rules[5] = new Rule(-4, new int[]{-5,-6,40,-7,14});
    rules[6] = new Rule(-4, new int[]{-5,-6,40,-8});
    rules[7] = new Rule(-5, new int[]{4});
    rules[8] = new Rule(-6, new int[]{});
    rules[9] = new Rule(-6, new int[]{13,-9});
    rules[10] = new Rule(-9, new int[]{19});
    rules[11] = new Rule(-9, new int[]{20});
    rules[12] = new Rule(-9, new int[]{21});
    rules[13] = new Rule(-9, new int[]{22});
    rules[14] = new Rule(-9, new int[]{23});
    rules[15] = new Rule(-9, new int[]{24});
    rules[16] = new Rule(-9, new int[]{-10});
    rules[17] = new Rule(-9, new int[]{-11});
    rules[18] = new Rule(-9, new int[]{-12});
    rules[19] = new Rule(-9, new int[]{-13});
    rules[20] = new Rule(-14, new int[]{-7});
    rules[21] = new Rule(-14, new int[]{-8});
    rules[22] = new Rule(-7, new int[]{-15});
    rules[23] = new Rule(-7, new int[]{-15,27,-7});
    rules[24] = new Rule(-7, new int[]{-15,28,-7});
    rules[25] = new Rule(-7, new int[]{-15,29,-7});
    rules[26] = new Rule(-7, new int[]{-15,30,-7});
    rules[27] = new Rule(-7, new int[]{-15,31,-7});
    rules[28] = new Rule(-7, new int[]{-15,32,-7});
    rules[29] = new Rule(-7, new int[]{-15,33,-7});
    rules[30] = new Rule(-7, new int[]{-15,34,-7});
    rules[31] = new Rule(-7, new int[]{-15,35,-7});
    rules[32] = new Rule(-7, new int[]{-15,17,-7});
    rules[33] = new Rule(-7, new int[]{-15,18,-7});
    rules[34] = new Rule(-7, new int[]{-15,15,-7});
    rules[35] = new Rule(-7, new int[]{-15,16,-7});
    rules[36] = new Rule(-7, new int[]{18,-15});
    rules[37] = new Rule(-7, new int[]{-15,57,-15});
    rules[38] = new Rule(-15, new int[]{-16});
    rules[39] = new Rule(-15, new int[]{-17});
    rules[40] = new Rule(-15, new int[]{-15,-18});
    rules[41] = new Rule(-16, new int[]{-19});
    rules[42] = new Rule(-16, new int[]{-20});
    rules[43] = new Rule(-16, new int[]{-21});
    rules[44] = new Rule(-16, new int[]{-22});
    rules[45] = new Rule(-16, new int[]{-23});
    rules[46] = new Rule(-19, new int[]{5});
    rules[47] = new Rule(-19, new int[]{6});
    rules[48] = new Rule(-19, new int[]{7});
    rules[49] = new Rule(-19, new int[]{8});
    rules[50] = new Rule(-19, new int[]{9});
    rules[51] = new Rule(-19, new int[]{10});
    rules[52] = new Rule(-19, new int[]{-5});
    rules[53] = new Rule(-20, new int[]{41,-7,42,-14,43,-14,44});
    rules[54] = new Rule(-8, new int[]{36,51,-24,52,-6,-25});
    rules[55] = new Rule(-24, new int[]{});
    rules[56] = new Rule(-24, new int[]{-26});
    rules[57] = new Rule(-26, new int[]{-27});
    rules[58] = new Rule(-26, new int[]{-26,12,-27});
    rules[59] = new Rule(-27, new int[]{-5,13,-9});
    rules[60] = new Rule(-25, new int[]{37,-28,44});
    rules[61] = new Rule(-25, new int[]{26,51,-14,52});
    rules[62] = new Rule(-28, new int[]{-29});
    rules[63] = new Rule(-28, new int[]{-28,-29});
    rules[64] = new Rule(-29, new int[]{-17,14});
    rules[65] = new Rule(-29, new int[]{-30});
    rules[66] = new Rule(-29, new int[]{-4});
    rules[67] = new Rule(-29, new int[]{-31});
    rules[68] = new Rule(-29, new int[]{-32});
    rules[69] = new Rule(-29, new int[]{-33});
    rules[70] = new Rule(-29, new int[]{-34});
    rules[71] = new Rule(-29, new int[]{-35});
    rules[72] = new Rule(-29, new int[]{-36});
    rules[73] = new Rule(-17, new int[]{-15,51,-37,52});
    rules[74] = new Rule(-37, new int[]{});
    rules[75] = new Rule(-37, new int[]{-38});
    rules[76] = new Rule(-38, new int[]{-14});
    rules[77] = new Rule(-38, new int[]{-38,12,-14});
    rules[78] = new Rule(-30, new int[]{-15,25,-14,14});
    rules[79] = new Rule(-31, new int[]{41,-7,42,-28,44});
    rules[80] = new Rule(-31, new int[]{41,-7,42,-28,43,-28,44});
    rules[81] = new Rule(-32, new int[]{-39,48,-28,44});
    rules[82] = new Rule(-39, new int[]{});
    rules[83] = new Rule(-39, new int[]{46,-5,47,-7});
    rules[84] = new Rule(-39, new int[]{46,-7});
    rules[85] = new Rule(-39, new int[]{45,-7});
    rules[86] = new Rule(-33, new int[]{38,14});
    rules[87] = new Rule(-33, new int[]{38,-14,14});
    rules[88] = new Rule(-34, new int[]{49,14});
    rules[89] = new Rule(-35, new int[]{50,14});
    rules[90] = new Rule(-36, new int[]{39,51,-37,52,14});
    rules[91] = new Rule(-21, new int[]{53,-37,54});
    rules[92] = new Rule(-22, new int[]{55,-40,56});
    rules[93] = new Rule(-40, new int[]{});
    rules[94] = new Rule(-40, new int[]{-41});
    rules[95] = new Rule(-40, new int[]{-40,12,-41});
    rules[96] = new Rule(-41, new int[]{-14,13,-14});
    rules[97] = new Rule(-23, new int[]{51,-42,52});
    rules[98] = new Rule(-42, new int[]{-43});
    rules[99] = new Rule(-42, new int[]{-42,12,-43});
    rules[100] = new Rule(-43, new int[]{-5,40,-14});
    rules[101] = new Rule(-43, new int[]{-14});
    rules[102] = new Rule(-18, new int[]{53,-14,54});
    rules[103] = new Rule(-18, new int[]{11,-5});
    rules[104] = new Rule(-18, new int[]{11,6});
    rules[105] = new Rule(-10, new int[]{36,51,-44,52,13,-9});
    rules[106] = new Rule(-44, new int[]{});
    rules[107] = new Rule(-44, new int[]{-9});
    rules[108] = new Rule(-44, new int[]{-44,12,-9});
    rules[109] = new Rule(-12, new int[]{53,-9,54});
    rules[110] = new Rule(-11, new int[]{51,-44,52});
    rules[111] = new Rule(-13, new int[]{55,-9,13,-9,56});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)ETokens.ERROR, (int)ETokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // starting -> dec_list, EOF
#line 40 "FParser/gppg/grammar.y"
                           { CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
#line default
        break;
      case 3: // dec_list -> declaration
#line 43 "FParser/gppg/grammar.y"
                        { CurrentSemanticValue = new DeclarationStatementList((DeclarationStatement)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 4: // dec_list -> dec_list, declaration
#line 44 "FParser/gppg/grammar.y"
                           { ((DeclarationStatementList)ValueStack[ValueStack.Depth-2]).statements.Add((DeclarationStatement)ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
#line default
        break;
      case 5: // declaration -> identifier, opt_type, IS, expr, SEMICOLON
#line 47 "FParser/gppg/grammar.y"
                                                    { CurrentSemanticValue = new DeclarationStatement((Identifier)ValueStack[ValueStack.Depth-5], (FType)ValueStack[ValueStack.Depth-4], (FExpression)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 6: // declaration -> identifier, opt_type, IS, func_def
#line 48 "FParser/gppg/grammar.y"
                                       { CurrentSemanticValue = new DeclarationStatement((Identifier)ValueStack[ValueStack.Depth-4], (FType)ValueStack[ValueStack.Depth-3], (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 7: // identifier -> ID
#line 51 "FParser/gppg/grammar.y"
                   { CurrentSemanticValue = new Identifier(((TokenValue)ValueStack[ValueStack.Depth-1])[0].ToString()); }
#line default
        break;
      case 8: // opt_type -> /* empty */
#line 54 "FParser/gppg/grammar.y"
                        { CurrentSemanticValue = null; }
#line default
        break;
      case 9: // opt_type -> COLON, type
#line 55 "FParser/gppg/grammar.y"
                 { CurrentSemanticValue = (FType) ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 10: // type -> INTEGER
#line 58 "FParser/gppg/grammar.y"
                  { CurrentSemanticValue = new IntegerType(); }
#line default
        break;
      case 11: // type -> COMPLEX
#line 59 "FParser/gppg/grammar.y"
               { CurrentSemanticValue = new ComplexType(); }
#line default
        break;
      case 12: // type -> RATIONAL
#line 60 "FParser/gppg/grammar.y"
               { CurrentSemanticValue = new RationalType(); }
#line default
        break;
      case 13: // type -> REAL
#line 61 "FParser/gppg/grammar.y"
            { CurrentSemanticValue = new RealType(); }
#line default
        break;
      case 14: // type -> STRING
#line 62 "FParser/gppg/grammar.y"
              { CurrentSemanticValue = new StringType(); }
#line default
        break;
      case 15: // type -> BOOLEAN
#line 63 "FParser/gppg/grammar.y"
               { CurrentSemanticValue = new BooleanType(); }
#line default
        break;
      case 16: // type -> func_type
#line 64 "FParser/gppg/grammar.y"
                { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 17: // type -> tuple_type
#line 65 "FParser/gppg/grammar.y"
                 { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 18: // type -> array_type
#line 66 "FParser/gppg/grammar.y"
                 { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 19: // type -> map_type
#line 67 "FParser/gppg/grammar.y"
               { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 20: // expr2 -> expr
#line 70 "FParser/gppg/grammar.y"
                { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 21: // expr2 -> func_def
#line 71 "FParser/gppg/grammar.y"
               { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 22: // expr -> secondary
#line 74 "FParser/gppg/grammar.y"
                        { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 23: // expr -> secondary, LESS, expr
#line 75 "FParser/gppg/grammar.y"
                             { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new LessOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 24: // expr -> secondary, LESSEQUAL, expr
#line 76 "FParser/gppg/grammar.y"
                                { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new LessEqualOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 25: // expr -> secondary, GREATER, expr
#line 77 "FParser/gppg/grammar.y"
                               { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new GreaterOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 26: // expr -> secondary, GREATEREQUAL, expr
#line 78 "FParser/gppg/grammar.y"
                                   { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new GreaterEqualOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 27: // expr -> secondary, EQUAL, expr
#line 79 "FParser/gppg/grammar.y"
                             { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new EqualOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 28: // expr -> secondary, NOTEQUAL, expr
#line 80 "FParser/gppg/grammar.y"
                                { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new NotEqualOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 29: // expr -> secondary, AND, expr
#line 81 "FParser/gppg/grammar.y"
                            { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new AndOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 30: // expr -> secondary, OR, expr
#line 82 "FParser/gppg/grammar.y"
                           { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new OrOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 31: // expr -> secondary, XOR, expr
#line 83 "FParser/gppg/grammar.y"
                            { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new XorOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 32: // expr -> secondary, PLUS, expr
#line 84 "FParser/gppg/grammar.y"
                             { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new PlusOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 33: // expr -> secondary, MINUS, expr
#line 85 "FParser/gppg/grammar.y"
                             { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new MinusOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 34: // expr -> secondary, STAR, expr
#line 86 "FParser/gppg/grammar.y"
                             { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new StarOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 35: // expr -> secondary, SLASH, expr
#line 87 "FParser/gppg/grammar.y"
                             { CurrentSemanticValue = new BinaryOperatorExpression((FSecondary)ValueStack[ValueStack.Depth-3], new SlashOperator(), (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 36: // expr -> MINUS, secondary
#line 88 "FParser/gppg/grammar.y"
                                   { CurrentSemanticValue = new NegativeExpression((FSecondary)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 37: // expr -> secondary, ELLIPSIS, secondary
#line 89 "FParser/gppg/grammar.y"
                                    { CurrentSemanticValue = new EllipsisExpression((FSecondary)ValueStack[ValueStack.Depth-3], (FSecondary)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 38: // secondary -> primary
#line 92 "FParser/gppg/grammar.y"
                         { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 39: // secondary -> func_call
#line 93 "FParser/gppg/grammar.y"
                   { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 40: // secondary -> secondary, indexer
#line 94 "FParser/gppg/grammar.y"
                         { CurrentSemanticValue = new IndexedAccess((FSecondary)ValueStack[ValueStack.Depth-2], (Indexer)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 41: // primary -> value
#line 97 "FParser/gppg/grammar.y"
                      { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 42: // primary -> cond
#line 98 "FParser/gppg/grammar.y"
              { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 43: // primary -> array_def
#line 100 "FParser/gppg/grammar.y"
                  { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 44: // primary -> map_def
#line 101 "FParser/gppg/grammar.y"
                 { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 45: // primary -> tuple_def
#line 102 "FParser/gppg/grammar.y"
                  { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 46: // value -> BOOLEAN_VALUE
#line 106 "FParser/gppg/grammar.y"
                         { CurrentSemanticValue = new BooleanValue((bool) ((TokenValue)ValueStack[ValueStack.Depth-1])[0]); }
#line default
        break;
      case 47: // value -> INTEGER_VALUE
#line 107 "FParser/gppg/grammar.y"
                     { CurrentSemanticValue = new IntegerValue((int) ((TokenValue)ValueStack[ValueStack.Depth-1])[0]); }
#line default
        break;
      case 48: // value -> REAL_VALUE
#line 108 "FParser/gppg/grammar.y"
                   { CurrentSemanticValue = new RealValue((double) ((TokenValue)ValueStack[ValueStack.Depth-1])[0]); }
#line default
        break;
      case 49: // value -> RATIONAL_VALUE
#line 109 "FParser/gppg/grammar.y"
                      { CurrentSemanticValue = new RationalValue((int) ((TokenValue)ValueStack[ValueStack.Depth-1])[0], (int) ((TokenValue)ValueStack[ValueStack.Depth-1])[1]); }
#line default
        break;
      case 50: // value -> COMPLEX_VALUE
#line 110 "FParser/gppg/grammar.y"
                     { CurrentSemanticValue = new ComplexValue((double) ((TokenValue)ValueStack[ValueStack.Depth-1])[0], (double) ((TokenValue)ValueStack[ValueStack.Depth-1])[1]); }
#line default
        break;
      case 51: // value -> STRING_VALUE
#line 111 "FParser/gppg/grammar.y"
                    { CurrentSemanticValue = new StringValue((string) ((TokenValue)ValueStack[ValueStack.Depth-1])[0]); }
#line default
        break;
      case 52: // value -> identifier
#line 112 "FParser/gppg/grammar.y"
                   { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 53: // cond -> IF, expr, THEN, expr2, ELSE, expr2, END
#line 115 "FParser/gppg/grammar.y"
                                           { CurrentSemanticValue = new Conditional((FExpression)ValueStack[ValueStack.Depth-6], (FExpression)ValueStack[ValueStack.Depth-4], (FExpression)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 54: // func_def -> FUNC, LROUND, opt_params, RROUND, opt_type, func_body
#line 118 "FParser/gppg/grammar.y"
                                                             { CurrentSemanticValue = new FunctionDefinition((ParameterList)ValueStack[ValueStack.Depth-4], (FType)ValueStack[ValueStack.Depth-2], (StatementList)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 55: // opt_params -> /* empty */
#line 121 "FParser/gppg/grammar.y"
                               { CurrentSemanticValue = new ParameterList(); }
#line default
        break;
      case 56: // opt_params -> param_list
#line 122 "FParser/gppg/grammar.y"
                      { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 57: // param_list -> param
#line 125 "FParser/gppg/grammar.y"
                           { CurrentSemanticValue = new ParameterList((Parameter)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 58: // param_list -> param_list, COMMA, param
#line 126 "FParser/gppg/grammar.y"
                                { ((ParameterList)ValueStack[ValueStack.Depth-3]).parameters.Add((Parameter)ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; }
#line default
        break;
      case 59: // param -> identifier, COLON, type
#line 129 "FParser/gppg/grammar.y"
                                     { CurrentSemanticValue = new Parameter((Identifier)ValueStack[ValueStack.Depth-3], (FType)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 60: // func_body -> DO, stm_list, END
#line 132 "FParser/gppg/grammar.y"
                                 { CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
#line default
        break;
      case 61: // func_body -> ARROW, LROUND, expr2, RROUND
#line 133 "FParser/gppg/grammar.y"
                                 { CurrentSemanticValue = new StatementList(new ExpressionStatement((FExpression)ValueStack[ValueStack.Depth-2])); }
#line default
        break;
      case 62: // stm_list -> statement
#line 136 "FParser/gppg/grammar.y"
                           { CurrentSemanticValue = new StatementList((FStatement)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 63: // stm_list -> stm_list, statement
#line 137 "FParser/gppg/grammar.y"
                            { ((StatementList)ValueStack[ValueStack.Depth-2]).statements.Add((FStatement)ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
#line default
        break;
      case 64: // statement -> func_call, SEMICOLON
#line 140 "FParser/gppg/grammar.y"
                                    { CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
#line default
        break;
      case 65: // statement -> assignment
#line 141 "FParser/gppg/grammar.y"
                      { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 66: // statement -> declaration
#line 142 "FParser/gppg/grammar.y"
                       { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 67: // statement -> if_stm
#line 143 "FParser/gppg/grammar.y"
                   { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 68: // statement -> loop_stm
#line 144 "FParser/gppg/grammar.y"
                    { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 69: // statement -> return_stm
#line 145 "FParser/gppg/grammar.y"
                      { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 70: // statement -> break_stm
#line 146 "FParser/gppg/grammar.y"
                     { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 71: // statement -> cont_stm
#line 147 "FParser/gppg/grammar.y"
                    { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 72: // statement -> print_stm
#line 148 "FParser/gppg/grammar.y"
                     { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 73: // func_call -> secondary, LROUND, opt_exprs, RROUND
#line 151 "FParser/gppg/grammar.y"
                                              { CurrentSemanticValue = new FunctionCall((FSecondary)ValueStack[ValueStack.Depth-4], (ExpressionList)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 74: // opt_exprs -> /* empty */
#line 154 "FParser/gppg/grammar.y"
                              { CurrentSemanticValue = new ExpressionList(); }
#line default
        break;
      case 75: // opt_exprs -> expr_list
#line 155 "FParser/gppg/grammar.y"
                     { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 76: // expr_list -> expr2
#line 158 "FParser/gppg/grammar.y"
                         { CurrentSemanticValue = new ExpressionList((FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 77: // expr_list -> expr_list, COMMA, expr2
#line 159 "FParser/gppg/grammar.y"
                              { ((ExpressionList)ValueStack[ValueStack.Depth-3]).expressions.Add((FExpression)ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; }
#line default
        break;
      case 78: // assignment -> secondary, ASSIGN, expr2, SEMICOLON
#line 162 "FParser/gppg/grammar.y"
                                               { CurrentSemanticValue = new AssignmentStatemt((FSecondary)ValueStack[ValueStack.Depth-4], (FExpression)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 79: // if_stm -> IF, expr, THEN, stm_list, END
#line 165 "FParser/gppg/grammar.y"
                                          { CurrentSemanticValue = new IfStatement((FExpression)ValueStack[ValueStack.Depth-4], (StatementList)ValueStack[ValueStack.Depth-2], new StatementList()); }
#line default
        break;
      case 80: // if_stm -> IF, expr, THEN, stm_list, ELSE, stm_list, END
#line 166 "FParser/gppg/grammar.y"
                                               { CurrentSemanticValue = new IfStatement((FExpression)ValueStack[ValueStack.Depth-6], (StatementList)ValueStack[ValueStack.Depth-4], (StatementList)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 81: // loop_stm -> loop_header, LOOP, stm_list, END
#line 169 "FParser/gppg/grammar.y"
                                          { CurrentSemanticValue = new LoopStatement((FLoopHeader)ValueStack[ValueStack.Depth-4], (StatementList)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 82: // loop_header -> /* empty */
#line 172 "FParser/gppg/grammar.y"
                                { CurrentSemanticValue = null; }
#line default
        break;
      case 83: // loop_header -> FOR, identifier, IN, expr
#line 173 "FParser/gppg/grammar.y"
                               { CurrentSemanticValue = new ForHeader((Identifier)ValueStack[ValueStack.Depth-3], (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 84: // loop_header -> FOR, expr
#line 174 "FParser/gppg/grammar.y"
                    { CurrentSemanticValue = new ForHeader(null, (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 85: // loop_header -> WHILE, expr
#line 175 "FParser/gppg/grammar.y"
                      { CurrentSemanticValue = new WhileHeader((FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 86: // return_stm -> RETURN, SEMICOLON
#line 178 "FParser/gppg/grammar.y"
                                  { CurrentSemanticValue = new ReturnStatement(); }
#line default
        break;
      case 87: // return_stm -> RETURN, expr2, SEMICOLON
#line 179 "FParser/gppg/grammar.y"
                               { CurrentSemanticValue = new ReturnStatement((FExpression)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 88: // break_stm -> BREAK, SEMICOLON
#line 182 "FParser/gppg/grammar.y"
                                 { CurrentSemanticValue = new BreakStatement(); }
#line default
        break;
      case 89: // cont_stm -> CONTINUE, SEMICOLON
#line 185 "FParser/gppg/grammar.y"
                                  { CurrentSemanticValue = new ContinueStatement(); }
#line default
        break;
      case 90: // print_stm -> PRINT, LROUND, opt_exprs, RROUND, SEMICOLON
#line 188 "FParser/gppg/grammar.y"
                                                     { CurrentSemanticValue = new PrintStatement((ExpressionList)ValueStack[ValueStack.Depth-3]); }
#line default
        break;
      case 91: // array_def -> LSQUARE, opt_exprs, RSQUARE
#line 191 "FParser/gppg/grammar.y"
                                         { CurrentSemanticValue = new ArrayDefinition((ExpressionList)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 92: // map_def -> LCURLY, pair_list, RCURLY
#line 194 "FParser/gppg/grammar.y"
                                      { CurrentSemanticValue = new MapDefinition((ExpressionPairList)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 93: // pair_list -> /* empty */
#line 197 "FParser/gppg/grammar.y"
                              { CurrentSemanticValue = new ExpressionPairList(); }
#line default
        break;
      case 94: // pair_list -> pair
#line 198 "FParser/gppg/grammar.y"
                 { CurrentSemanticValue = new ExpressionPairList((ExpressionPair)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 95: // pair_list -> pair_list, COMMA, pair
#line 199 "FParser/gppg/grammar.y"
                             { ((ExpressionPairList)ValueStack[ValueStack.Depth-3]).pairs.Add((ExpressionPair)ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; }
#line default
        break;
      case 96: // pair -> expr2, COLON, expr2
#line 202 "FParser/gppg/grammar.y"
                              { CurrentSemanticValue = new ExpressionPair((FExpression)ValueStack[ValueStack.Depth-3], (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 97: // tuple_def -> LROUND, tuple_elist, RROUND
#line 205 "FParser/gppg/grammar.y"
                                        { CurrentSemanticValue = new TupleDefinition((TupleElementList)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 98: // tuple_elist -> tuple_elem
#line 208 "FParser/gppg/grammar.y"
                               { CurrentSemanticValue = new TupleElementList((TupleElement)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 99: // tuple_elist -> tuple_elist, COMMA, tuple_elem
#line 209 "FParser/gppg/grammar.y"
                                   { ((TupleElementList)ValueStack[ValueStack.Depth-3]).elements.Add((TupleElement)ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; }
#line default
        break;
      case 100: // tuple_elem -> identifier, IS, expr2
#line 212 "FParser/gppg/grammar.y"
                                     { CurrentSemanticValue = new TupleElement((Identifier)ValueStack[ValueStack.Depth-3], (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 101: // tuple_elem -> expr2
#line 213 "FParser/gppg/grammar.y"
                  { CurrentSemanticValue = new TupleElement(null, (FExpression)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 102: // indexer -> LSQUARE, expr2, RSQUARE
#line 216 "FParser/gppg/grammar.y"
                                    { CurrentSemanticValue = new SquaresIndexer((FExpression)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 103: // indexer -> DOT, identifier
#line 217 "FParser/gppg/grammar.y"
                         { CurrentSemanticValue = new DotIndexer((Identifier)ValueStack[ValueStack.Depth-1], null);}
#line default
        break;
      case 104: // indexer -> DOT, INTEGER_VALUE
#line 218 "FParser/gppg/grammar.y"
                           { CurrentSemanticValue = new DotIndexer(null, new IntegerValue((int)((TokenValue)ValueStack[ValueStack.Depth-1])[0])); }
#line default
        break;
      case 105: // func_type -> FUNC, LROUND, type_list, RROUND, COLON, type
#line 221 "FParser/gppg/grammar.y"
                                                     { CurrentSemanticValue = new FunctionType((TypeList)ValueStack[ValueStack.Depth-4], (FType)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 106: // type_list -> /* empty */
#line 224 "FParser/gppg/grammar.y"
                              { CurrentSemanticValue = new TypeList(); }
#line default
        break;
      case 107: // type_list -> type
#line 225 "FParser/gppg/grammar.y"
                 { CurrentSemanticValue = new TypeList((FType)ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 108: // type_list -> type_list, COMMA, type
#line 226 "FParser/gppg/grammar.y"
                             { ((TypeList)ValueStack[ValueStack.Depth-3]).types.Add((FType)ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; }
#line default
        break;
      case 109: // array_type -> LSQUARE, type, RSQUARE
#line 229 "FParser/gppg/grammar.y"
                                      { CurrentSemanticValue = new ArrayType((FType)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 110: // tuple_type -> LROUND, type_list, RROUND
#line 232 "FParser/gppg/grammar.y"
                                         { CurrentSemanticValue = new TupleType((TypeList)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
      case 111: // map_type -> LCURLY, type, COLON, type, RCURLY
#line 235 "FParser/gppg/grammar.y"
                                           { CurrentSemanticValue = new MapType((FType)ValueStack[ValueStack.Depth-4], (FType)ValueStack[ValueStack.Depth-2]); }
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((ETokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((ETokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
